### ISSUE TITLE
Incorrect temperature displayed 

### ISSUE THREAD

**Issue by a19i23** [lukasroegner/homebridge-dyson-pure-cool#163]
When I try and set the temperature in the home app for my dyson heater/purifier can't get to 71 degrees in the temperature wheel. 

This is what it looks like in home app
![image](https://user-images.githubusercontent.com/6509090/108611959-dfafdd80-7398-11eb-81b4-21671f78b7f3.png)

and this is what it looks like in the dyson link app
![image](https://user-images.githubusercontent.com/6509090/108611973-f6563480-7398-11eb-8211-35e44512824b.png)

The second picture shows that the Dyson temperature is correctly set to 71 degrees but in the home app it says 72. I see this for other odd number temperatures for some reason but not all. If I change to 70 in home app and then go to one click above that, it reads 72 but correctly changes in dyson app to 71. If I click one above in home app from where it currently is 72 (but really 71) it reads 72 again and correctly reflects 72 in dyson app. 

So it works but some of the numbers are not displayed correctly in the home app which was really confusing when I first installed the plugin. Thanks for any feedback and/or a fix 😃

**Comment by jakemauer** [comment]
I see this in my HP04 on version 1.8.7 as well.

**Comment by lukasroegner** [comment]
Issues with setting the temperature in Fahrenheit have been fixed in version 2.2.0

**Comment by jakemauer** [comment]
Thanks Lukas!

**Comment by a19i23** [comment]
Thanks Lukas. I just updated to v2.4.0 and I'm still seeing the same issue. Do I have to do something special to make it work?

**Comment by lukasroegner** [comment]
Maybe @mpiotrowski could take a look at it, he provided the PR for enhancing Fahrenheit handling?

**Comment by lukasroegner** [comment]
@a19i23 I don't own a Dyson heating device, but managed to build a test setup: It works for me.
Please make sure that you've set the new setting `useFahrenheit` to `true`.

**Comment by a19i23** [comment]
Ok I'll give it a try, thanks!

**Comment by a19i23** [comment]
It did work after enabling that setting, thanks!
