### ISSUE TITLE
characteristic was expected valid number and received NaN

### ISSUE THREAD

**Issue by NogginTheNog** [lukasroegner/homebridge-dyson-pure-cool#164]
[23/02/2021, 10:17:01] [homebridge-dyson-pure-cool] This plugin generated a warning from the characteristic 'PM2.5 Density': characteristic was expected valid number and received NaN. See https://git.io/JtMGR for more info.
[23/02/2021, 10:17:01] [homebridge-dyson-pure-cool] This plugin generated a warning from the characteristic 'PM10 Density': characteristic was expected valid number and received NaN. See https://git.io/JtMGR for more info.
[23/02/2021, 10:17:01] [homebridge-dyson-pure-cool] This plugin generated a warning from the characteristic 'VOC Density': characteristic was expected valid number and received NaN. See https://git.io/JtMGR for more info.
[23/02/2021, 10:17:01] [homebridge-dyson-pure-cool] This plugin generated a warning from the characteristic 'Nitrogen Dioxide Density': characteristic was expected valid number and received NaN. See https://git.io/JtMGR for more info

**Comment by NogginTheNog** [comment]
[23/02/2021, 11:22:51] [homebridge-dyson-pure-cool] This plugin generated a warning from the characteristic 'PM2.5 Density': characteristic was expected valid number and received NaN. See https://git.io/JtMGR for more info.
[23/02/2021, 11:22:51] [homebridge-dyson-pure-cool] Error: 
    at PM2_5Density.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at PM2_5Density.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1966:16)
    at PM2_5Density.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1365:20)
    at AirQualitySensor.Service.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:465:35)
    at MqttClient.<anonymous> (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/src/dyson-pure-cool-device.js:487:35)
    at MqttClient.emit (events.js:315:20)
    at MqttClient._handlePublish (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:940:12)
    at MqttClient._handlePacket (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:305:12)
    at work (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:261:12)
    at Writable.writable._write (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:271:5)
[23/02/2021, 11:22:51] [homebridge-dyson-pure-cool] This plugin generated a warning from the characteristic 'PM10 Density': characteristic was expected valid number and received NaN. See https://git.io/JtMGR for more info.
[23/02/2021, 11:22:51] [homebridge-dyson-pure-cool] Error: 
    at PM10Density.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at PM10Density.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1966:16)
    at PM10Density.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1365:20)
    at AirQualitySensor.Service.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:465:35)
    at MqttClient.<anonymous> (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/src/dyson-pure-cool-device.js:488:35)
    at MqttClient.emit (events.js:315:20)
    at MqttClient._handlePublish (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:940:12)
    at MqttClient._handlePacket (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:305:12)
    at work (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:261:12)
    at Writable.writable._write (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:271:5)
[23/02/2021, 11:22:51] [homebridge-dyson-pure-cool] This plugin generated a warning from the characteristic 'VOC Density': characteristic was expected valid number and received NaN. See https://git.io/JtMGR for more info.
[23/02/2021, 11:22:51] [homebridge-dyson-pure-cool] Error: 
    at VOCDensity.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at VOCDensity.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1966:16)
    at VOCDensity.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1365:20)
    at AirQualitySensor.Service.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:465:35)
    at MqttClient.<anonymous> (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/src/dyson-pure-cool-device.js:489:35)
    at MqttClient.emit (events.js:315:20)
    at MqttClient._handlePublish (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:940:12)
    at MqttClient._handlePacket (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:305:12)
    at work (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:261:12)
    at Writable.writable._write (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:271:5)
[23/02/2021, 11:22:51] [homebridge-dyson-pure-cool] This plugin generated a warning from the characteristic 'Nitrogen Dioxide Density': characteristic was expected valid number and received NaN. See https://git.io/JtMGR for more info.
[23/02/2021, 11:22:51] [homebridge-dyson-pure-cool] Error: 
    at NitrogenDioxideDensity.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at NitrogenDioxideDensity.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1966:16)
    at NitrogenDioxideDensity.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1365:20)
    at AirQualitySensor.Service.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:465:35)
    at MqttClient.<anonymous> (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/src/dyson-pure-cool-device.js:490:35)
    at MqttClient.emit (events.js:315:20)
    at MqttClient._handlePublish (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:940:12)
    at MqttClient._handlePacket (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:305:12)
    at work (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:261:12)
    at Writable.writable._write (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:271:5)

**Comment by MTBNoFear** [comment]
Same issue with me. This happend if ContinuousMonitoring is disabled. So would be great to avoid these warnings if ContinuousMonitoring is disabled and init the fields with a default value

**Comment by lukasroegner** [comment]
Fixed in 2.0.1

**Comment by CooperCGN** [comment]
I am still getting this error with 2.0.1. Installed.

![506BC0D0-7042-4569-A074-37421A7D18CA](https://user-images.githubusercontent.com/29116509/119223084-b9185480-baf7-11eb-95f2-1c25d87abe1b.jpeg)

**Comment by CSchmidtDD** [comment]
Can confirm this happens only for those two characteristics:

- 'PM10 Density': characteristic value expected valid finite number and received "NaN" (number)
- 'PM2.5 Density': characteristic value expected valid finite number and received "NaN" (number)

Maybe there is more to this issue.
