### ISSUE TITLE
[Feature Request] Support Chinese login flow

### ISSUE THREAD

**Issue by exsystem** [lukasroegner/homebridge-dyson-pure-cool#231]
We do not register an Dyson account with an E-mail address / password, instead, we use mobile phone number to register an account (no passwords need, use verification code sent from Dyson by SMS), how to use this plugin with such accounts?

account info example:
Mobile Phone Number: 13712345678
SMS Verification Code: 654321

also, I am using HP07 which seems not supported? 

Thanks :)

**Comment by jqcc88** [comment]
there seems to be a way in home assistant - so we may need to modify

**Comment by lukasroegner** [comment]
Please check out the latest version 2.5.0. When you open the credentials generator, there is a link at the bottom to start the login via mobile phone.

**Comment by xmasrain** [comment]
> Please check out the latest version 2.5.0. When you open the credentials generator, there is a link at the bottom to start the login via mobile phone.

Here I tried:
Error while receiving 2FA challenge ID. Status Code: 400

**Comment by xmasrain** [comment]
And I found that "+86" is needed

**Comment by xmasrain** [comment]
Failed at step2-cn ：“Check if account password/token is correct. ”
I typed correct SMS message， however it goes wrong for me

**Comment by lukasroegner** [comment]
Thank you for the feedback! I found a bug, that is now fixed in version 2.7.1.

**Comment by xmasrain** [comment]
Still failed at "Check if account password/token is correct."
![image](https://user-images.githubusercontent.com/58833842/154852583-ef60f8fd-c072-4f37-ba2f-f6e3a1c16870.png)

**Comment by lukasroegner** [comment]
There seems to be an issue with the Chinese Dyson API, maybe they changed the login flow: https://github.com/shenxn/libdyson/issues/20

**Comment by exsystem** [comment]
I have tested now as in ver2.7.1, it is working, thank you! 👍 
and you really should not changing the title, maybe this was a really issue in Chinese mainland part of China only... 😃 haha

**Comment by jqcc88** [comment]
Can someone help me get it setup for China - i do not even know how to add dyson fans
